### PR TITLE
Fixing spelling mistakes

### PR DESCRIPTION
**Pull request by Danyylka**
Description:
This pull request corrects two spelling errors in the codebase:

"amxiety" has been corrected to "anxiety."
"prevalant" has been corrected to "prevalent."
These changes ensure proper spelling and improve the overall clarity and professionalism of the project.

### CODE REVIEW

**Comment by Danyylka** [comment]
Hi team! Could someone please review and merge my pull request? Let me know if any changes are needed. Thanks!

@jshufro 
@rex4539 
@remyroy 
@thorsteneb

**Comment by yorickdowne** [comment]
amxiety was deliberate, prevalent was a spelling error.

I am confused about these spelling PRs lately … likely AI driven, and what’s the aim?

**Comment by Danyylka** [comment]
I’m not actively creating commits and pull requests; I just noticed the error and decided to fix it. I hope this doesn’t cause any misunderstanding.

**Comment by yorickdowne** [comment]
Could you leave “amxiety” in place, it’s meant to be a Shiba reference. “Prevalent” does need the correction.

**Comment by Danyylka** [comment]
yes, of course I'll change that now

**Review by yorickdowne — APPROVED** [review]
Thanks

**Pull request merged**
