### PR TITLE
reverse hybrid MEV setup notes

### PR DESCRIPTION
**Pull request by b0a7**
add some notes about exposing API ports and using MEV boost in RocketPool reverse hybrid setup

### CODE REVIEW

**Comment by yorickdowne** [comment]
I'll need some hand-holding please. My understanding is that the VC does absolutely nothing with mev-boost, it's the CL that does.

Walk me through step by step please. Which port are you exposing on the RocketPool side, what service on the eth-docker side is connecting to it how?

**Comment by b0a7** [comment]
In eth-docker I just have a validator (Teku).
The first thing that I did was the eth-docker .env setup as per
https://eth-docker.net/Usage/Advanced
"If you are running a validator client only, such as with a RocketPool
"reverse hybrid" setup, then all you need to do is to set MEV_BOOST=true in
.env."

But I didn't see the lines like
     "Validator   *** x out of x validator registration(s) were
successfully sent to the builder network via the Beacon Node."
in the eth-docker validator until I exposed the MEV API port in 'rocketpool
service config'.

RocketPool MEV Boost settings are as follows:
Enable MEV Boost (checkbox YES)
MEV-Boost Mode: Locally Managed
Selection Mode: Profile Mode
MEV Types checkboxes (unregulated all, unregulated no sandwich, regulated)
Port 18550
Expose API Port (checkbox YES)
Container: flashbots/mev-boost:version

The "Validator   *** x out of x validator registration(s) were successfully
sent to the builder network via the Beacon Node." lines were always there
in my RocketPool validator, but not in the eth-docker validator until I
checked the 'Expose API Port' checkbox.

Does it make any sense?

**Comment by yorickdowne** [comment]
That is odd. The VC does not connect to mev-boost at all, only the CL does. Can you share the `COMPOSE_FILE` you have in eth-docker, from `.env`?

**Comment by b0a7** [comment]
COMPOSE_FILE=teku-vc-only.yml:ext-network.yml

**Comment by b0a7** [comment]
If what I'm saying doesn't make sense I'm wondering if I did something
wrong like not restarting the validator after a change in the .env file or
something.  I don't think that's the case, but it was quite a few months
ago that I set it up, so not really fresh in my mind.

**Pull request closed without merging**
